HUSH-5723 github: setup TF in release workflow
This is needed for running unit tests with parallelism.

Otherwise tests fail (due to race) with the following error:

=== NAME  TestAccResourceMongoDBAccessCredential
    mongodb_access_credential_test.go:11: failed to create new working directory: unable to disable terraform-exec provider verification: fork/exec /tmp/plugintest-terraform2630751419/terraform: text file busy
--- FAIL: TestAccResourceMongoDBAccessCredential (2.77s)

`text file busy` error happens because one test tries to overwrite a
file that is currently being executed (terraform binary).